language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

env:
  global:
    # travis-encrypt -r martinmicunda/mm-angular-exception-handler COVERALLS_REPO_TOKEN=<value> --add env.global
    - secure: Saq4BCL/xYoepbAHIQbc4h/kwrgJuatQZls/L3imesXaC+NH5ayo8c79GtpbuiGLoCj2qXt66wqOiQiUec9KgLVrsKE2wRUU3LNbGC94H2OXUjBgfGV6lvW6LEIMW80PzWo/1xhY0VZVP/OP8qONwhnikIuOgAUDDIga2hEpT/E=

# starts xvfb on display port :99.0 (virtual display for Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# install dependencies necessary to run this build
install:
  - npm install
  - bower install

script:
  - gulp test

